name: Build and Publish EBI template

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 🔧 Install
        run: |
          npm ci
      - name: 🔧 Build
        run: |
          npm run build -- --public-url "."
      - name: 🚀 Deploy Demo
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          clean: true
      - name: 🚀 Deploy My talks
        if: github.ref == 'refs/heads/my-talks'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/ # The folder the action should deploy.
          target-folder: my-talks/
      - name: 📟 Building My talks
        if: github.ref == 'refs/heads/main'
        run: |
          gh workflow run publish.yml --ref v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
